[versions]
sadu = "2.3.9"
logback = "1.6.2"
jda = "6.5.0"
jdacommands = "5.1.1"
jdwebhooks = "2.0.0"
hikari = "7.1.0"
postgres = "42.7.13"
slf4j = "2.0.18"
jspecify = "1.0.1"
shadow = "9.6.1"
spotless = "8.9.0"

[libraries]
# Core
jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
jdacommands = { group = "io.github.kaktushose", name = "jda-commands", version.ref = "jdacommands" }
jdwebhooks = { group = "io.github.4drian3d", name = "jdwebhooks", version.ref = "jdwebhooks" }

# Database
hikari = { group = "com.zaxxer", name = "HikariCP", version.ref = "hikari" }
postgres = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }
sadu-postgresql = { group = "de.chojo.sadu", name = "sadu-postgresql", version.ref = "sadu" }
sadu-datasource = { group = "de.chojo.sadu", name = "sadu-datasource", version.ref = "sadu" }
sadu-queries = { group = "de.chojo.sadu", name = "sadu-queries", version.ref = "sadu" }
sadu-mapper = { group = "de.chojo.sadu", name = "sadu-mapper", version.ref = "sadu" }
sadu-updater = { group = "de.chojo.sadu", name = "sadu-updater", version.ref = "sadu" }

# Logging
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# Annotations
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }

[bundles]
logging = [
    "slf4j",
    "logback-core",
    "logback-classic"
]

database = [
    "hikari",
    "postgres",
    "sadu-postgresql",
    "sadu-datasource",
    "sadu-queries",
    "sadu-mapper",
    "sadu-updater"
]

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
